In [16]:
import numpy as np


In [12]:
#attributes of numpy
arr = np.array(((1,2),(3,"ABC")))   # value, datatype
print(arr)

print(arr.ndim)
print(arr.shape)
print(type(arr))
print(arr.dtype)

[['1' '2']
 ['3' 'ABC']]
2
(2, 2)
<class 'numpy.ndarray'>
<U21


In [13]:
# methods
arr = np.array(((1,2),(3,"ABC")))   # value, datatype  # to create array
# print(arr)

print(np.arange(3)) # start , stop , steps
print(np.random.rand(1,2)) # size
print(np.random.randint(0,10,12))   # start , end , element

[0 1 2]
[[0.61165743 0.30113326]]
[2 0 5 9 0 3 0 5 8 8 6 2]


In [ ]:
num = np.random.randint(0,10)
user = int(input("enter a number :"))
while(num != user):
    user = int(input("enter a number :"))
    if (num == user):
        print("you won")
    elif(num>user):
        print("guess a large number")
    else:
        print("guess a small number ")

In [15]:
# zeros
print(np.zeros((3,4,2),dtype=int))

# ones
print(np.ones((3,4,2),dtype=int))

[[[0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]]]
[[[1 1]
  [1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]
  [1 1]]]


In [17]:
arr=np.random.randint(1,10,12)
print(arr)
print(arr.shape)
print(arr.reshape(3,4))
print(arr)

[5 7 5 8 7 2 4 6 3 3 6 5]
(12,)
[[5 7 5 8]
 [7 2 4 6]
 [3 3 6 5]]
[5 7 5 8 7 2 4 6 3 3 6 5]


In [18]:
arr+arr   # opt overloading

array([10, 14, 10, 16, 14,  4,  8, 12,  6,  6, 12, 10])

In [19]:
list1=[1,2,3,4]
list1+list1

[1, 2, 3, 4, 1, 2, 3, 4]

In [20]:
# max, min, argmax, argmin
print(arr)
max(arr)
arr.max()     # np method
max(list1)    # py function

arr.min()
arr.argmax()
arr.argmin()
arr.mean()
arr.std()

[5 7 5 8 7 2 4 6 3 3 6 5]


np.float64(1.7539637649874324)

In [21]:
arr[3] # indexing
arr[2:5]    # slicing

array([5, 8, 7])

In [22]:
np.flip(arr)


array([5, 6, 3, 3, 6, 4, 2, 7, 8, 5, 7, 5])

In [24]:
arr=np.arange(1,30,2)

In [25]:
arr=arr.reshape(3,5)
arr

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29]])

In [26]:
print(arr.flatten())
print(arr.ravel())
print(arr)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]
[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]]


In [27]:
help(max)


Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value

    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more positional arguments, return the largest argument.

